use std::env;
use std::fs;
use std::fs::File;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

use regex::Regex;

fn get_git_version() -> Result<(u32, u32, u32, String), Box<dyn std::error::Error>> {
    // 1. Get the latest tag
    //    `git tag --list "v*.*.*"`: lists tags matching the pattern
    //    `--sort="-v:refname"`: sorts them by version name in descending order (semver-aware)
    let output = Command::new("git")
        .args(["tag", "--list", "v*.*.*", "--sort=-v:refname"])
        .output()?;

    if !output.status.success() {
        return Err(format!(
            "git command failed with status: {}\nstderr: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }

    let tags_stdout = String::from_utf8(output.stdout)?;
    let latest_tag_str = tags_stdout
        .lines()
        .next()
        .ok_or("No git tags found matching v*.*.*")?
        .trim();

    if latest_tag_str.is_empty() {
        return Err("Latest git tag string is empty".into());
    }

    // 2. Parse the tag (e.g., "v1.2.25")
    // Regex: starts with 'v', then digits for major, minor, revision
    let re = Regex::new(r"^v(\d+)\.(\d+)\.(\d+)$")?;
    let caps = re
        .captures(latest_tag_str)
        .ok_or_else(|| "Tag '{{latest_tag_str}}' does not match vX.X.X format".to_string())?;

    let major: u32 = caps.get(1).unwrap().as_str().parse()?;
    let minor: u32 = caps.get(2).unwrap().as_str().parse()?;
    let revision: u32 = caps.get(3).unwrap().as_str().parse()?;

    Ok((major, minor, revision, latest_tag_str.to_string()))
}

fn main() {
    let (major, minor, revision, _version_str) =
        get_git_version().expect("Failed to get git version");

    // 3. Generate the Rust code
    let generated_code = format!(
        r#"
// This file is automatically generated by build.rs
// Do not edit manually.

#[derive(Debug, Clone, Copy)]
pub struct BuildVersion {{
    pub major: u32,
    pub minor: u32,
    pub revision: u32,
}}

impl std::fmt::Display for BuildVersion {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        write!(f, "v{{}}.{{}}.{{}}", self.major, self.minor, self.revision)
    }}
}}

pub const BUILD_VERSION: BuildVersion = BuildVersion {{
    major: {major},
    minor: {minor},
    revision: {revision},
}};

// We also generate a static string version for direct use in clap
// This avoids needing to format it at runtime for the const version attribute.
pub const VERSION_STRING: &str = "v{major}.{minor}.{revision}";


// 1. Define a custom error type for parsing BuildVersion
#[derive(Debug, PartialEq, Eq)]
pub enum ParseBuildVersionError {{
    MissingVPrefix,
    InvalidFormat, // For wrong number of parts or general structure issues
    InvalidComponent(core::num::ParseIntError), // For errors parsing u32 components
}}

impl core::fmt::Display for ParseBuildVersionError {{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{
        match self {{
            Self::MissingVPrefix => {{
                write!(f, "version string must start with 'v'")
            }}
            Self::InvalidFormat => {{
                write!(f, "version string must be in 'vX.Y.Z' format with three numeric components")
            }}
            
            Self::InvalidComponent(e) => {{
                write!(f, "invalid numeric component in version string: {{e}}")
            }}
        }}
    }}
}}

impl std::error::Error for ParseBuildVersionError {{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {{
        match self {{
            Self::InvalidComponent(e) => Some(e),
            _ => None,
        }}
    }}
}}

// 2. Implement FromStr for BuildVersion
impl core::str::FromStr for BuildVersion {{
    type Err = ParseBuildVersionError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {{
        if !s.starts_with('v') {{
            return Err(ParseBuildVersionError::MissingVPrefix);
        }}

        // Strip the 'v' prefix
        let s_without_v = &s[1..];

        // Split the remaining string by '.'
        let mut parts = s_without_v.split('.');

        // Attempt to parse major, minor, and revision numbers
        let major_str = parts.next().ok_or(ParseBuildVersionError::InvalidFormat)?;
        let minor_str = parts.next().ok_or(ParseBuildVersionError::InvalidFormat)?;
        let revision_str = parts.next().ok_or(ParseBuildVersionError::InvalidFormat)?;

        // Ensure there are no more parts after major.minor.revision
        if parts.next().is_some() {{
            return Err(ParseBuildVersionError::InvalidFormat);
        }}

        let major = major_str.parse::<u32>().map_err(ParseBuildVersionError::InvalidComponent)?;
        let minor = minor_str.parse::<u32>().map_err(ParseBuildVersionError::InvalidComponent)?;
        let revision = revision_str.parse::<u32>().map_err(ParseBuildVersionError::InvalidComponent)?;

        Ok(Self {{ major, minor, revision }})
    }}
}}
"#
    );

    // 4. Write the generated code to a file in OUT_DIR
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR env var not set"));
    println!("cargo:out_dir={}", out_dir.display());
    let dest_path = out_dir.join("version_generated.rs");

    let mut file = File::create(&dest_path).expect("Failed to create version_generated.rs");
    file.write_all(generated_code.as_bytes())
        .expect("Failed to write to version_generated.rs");
    // 1. Check CI environment variable first
    // 2. Fallback to the local file generated by the bootstrap script
    let key_content = env::var("SIGNING_PUBLIC_KEY_PEM")
        .or_else(|_| fs::read_to_string("keys/signing_public.pem"))
        .unwrap_or_else(|_| "DEVELOPMENT_KEY".to_string());

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("signing_key.pem");
    fs::write(dest_path, key_content).unwrap();

    println!("cargo:rerun-if-env-changed=SIGNING_PUBLIC_KEY_PEM");
    println!("cargo:rerun-if-changed=keys/signing_public.pem");
}
