on: [push, pull_request]
name: Rust [binary_encrypter]
jobs:
  ci:
    uses: Liftnet2/gh-actions/.github/workflows/rust-ci.yml@v1
    with:
      extra-system-deps: 'cmake clang pkg-config libssl-dev openssl'
    secrets: inherit
